import { cp, mkdir, readFile, rm, chmod } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import { spawnSync } from 'node:child_process';

if (process.platform !== 'darwin') throw new Error('Veil packaging requires macOS.');
const root = resolve(import.meta.dirname, '..');
process.chdir(root);
const target = join(root, 'release', 'Veil Terminal.app');
const resources = join(target, 'Contents', 'Resources');
const appRoot = join(resources, 'app');
const version = (await readFile(join(root, 'node_modules/electron/dist/version'), 'utf8')).trim();
const appVersion = JSON.parse(await readFile(join(root, 'package.json'), 'utf8')).version;
if (!/^\d+\.\d+\.\d+$/.test(appVersion)) throw new Error('Release version must be major.minor.patch');
const headersRoot = join(root, '.cache/electron-headers');
function run(command, args) {
  const result = spawnSync(command, args, { stdio:'inherit', cwd:root });
  if (result.error) throw result.error;
  if (result.status !== 0) throw new Error(`${command} exited ${result.status}`);
}

// Fetch headers matching the locked Electron runtime; keep the cache local.
run(process.execPath, [join(root, 'node_modules/node-gyp/bin/node-gyp.js'), 'install',
  '--ensure', `--target=${version}`, '--dist-url=https://electronjs.org/headers', `--devdir=${headersRoot}`]);
await mkdir(join(root, 'native/build'), { recursive:true });
run('xcrun', ['clang++', '-std=c++17', '-ObjC++', '-mmacosx-version-min=12.0', '-dynamiclib', '-undefined', 'dynamic_lookup',
  '-DNAPI_DISABLE_CPP_EXCEPTIONS', '-I', join(headersRoot, version, 'include/node'),
  '-I', join(root, 'node_modules/node-addon-api'), '-framework', 'AppKit', '-framework', 'CoreGraphics',
  join(root, 'native/veil_blur.mm'), '-o', join(root, 'native/build/veil_blur.node')]);

// This exact output bundle is generated by this script, never an installed app.
await mkdir(join(root, 'release'), { recursive:true });
await rm(target, { recursive:true, force:true });
await cp(join(root, 'node_modules/electron/dist/Electron.app'), target, { recursive:true, verbatimSymlinks:true });
await rm(join(resources, 'default_app.asar'), { force:true });
await mkdir(appRoot, { recursive:true });
await cp(join(root, 'electron'), join(appRoot, 'electron'), { recursive:true });
await cp(join(root, 'renderer'), join(appRoot, 'dist/client'), { recursive:true });
await cp(join(root, 'bin'), join(appRoot, 'bin'), { recursive:true });
await cp(join(root, 'package.json'), join(appRoot, 'package.json'));
await cp(join(root, 'native/build/veil_blur.node'), join(appRoot, 'native/veil_blur.node'));
for (const dependency of ['node-pty', 'node-addon-api']) {
  await cp(join(root, 'node_modules', dependency), join(appRoot, 'node_modules', dependency), {recursive:true});
}
await chmod(join(appRoot, 'bin/veil'), 0o755);
run(process.execPath, [join(root, 'scripts/build-veil-image.mjs')]);
run(process.execPath, [join(root, 'scripts/patch-veil-appearance.mjs')]);
run(process.execPath, [join(root, 'scripts/patch-veil-terminal-persistence.mjs')]);
run(process.execPath, [join(root, 'scripts/patch-veil-background.mjs')]);
await cp(join(root, 'assets/Info.plist'), join(target, 'Contents/Info.plist'));
for (const key of ['CFBundleShortVersionString', 'CFBundleVersion']) {
  run('/usr/libexec/PlistBuddy', ['-c', `Set :${key} ${appVersion}`, join(target, 'Contents/Info.plist')]);
}
await cp(join(root, 'assets/veil.icns'), join(resources, 'electron.icns'));
await cp(join(root, 'THIRD_PARTY_NOTICES.md'), join(resources, 'THIRD_PARTY_NOTICES.md'));
await cp(join(root, 'licenses'), join(resources, 'licenses'), { recursive:true });
await cp(join(root, 'node_modules/electron/dist/LICENSES.chromium.html'), join(resources, 'LICENSES.chromium.html'));
run('codesign', ['--force', '--deep', '--sign', '-', target]);
run('codesign', ['--verify', '--deep', '--strict', target]);
console.log(`Built ${target}\nDrag this app into Applications to install it.`);
